// flow-typed signature: 0f01283096b781192726000a5fc38a34
// flow-typed version: <<STUB>>/remotedev-rn-debugger_v^0.8.3/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remotedev-rn-debugger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remotedev-rn-debugger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remotedev-rn-debugger/bin/cli' {
  declare module.exports: any;
}

declare module 'remotedev-rn-debugger/bundle' {
  declare module.exports: any;
}

declare module 'remotedev-rn-debugger/lib/injectDebugger' {
  declare module.exports: any;
}

declare module 'remotedev-rn-debugger/lib/injectServer' {
  declare module.exports: any;
}

declare module 'remotedev-rn-debugger/lib/main' {
  declare module.exports: any;
}

declare module 'remotedev-rn-debugger/lib/runServer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remotedev-rn-debugger/bin/cli.js' {
  declare module.exports: $Exports<'remotedev-rn-debugger/bin/cli'>;
}
declare module 'remotedev-rn-debugger/bundle.js' {
  declare module.exports: $Exports<'remotedev-rn-debugger/bundle'>;
}
declare module 'remotedev-rn-debugger/lib/injectDebugger.js' {
  declare module.exports: $Exports<'remotedev-rn-debugger/lib/injectDebugger'>;
}
declare module 'remotedev-rn-debugger/lib/injectServer.js' {
  declare module.exports: $Exports<'remotedev-rn-debugger/lib/injectServer'>;
}
declare module 'remotedev-rn-debugger/lib/main.js' {
  declare module.exports: $Exports<'remotedev-rn-debugger/lib/main'>;
}
declare module 'remotedev-rn-debugger/lib/runServer.js' {
  declare module.exports: $Exports<'remotedev-rn-debugger/lib/runServer'>;
}
